// pch.h
//
// Generated by C DriverWizard 3.2.0 (Build 2485)
// Requires DDK Only
// File created on 11/15/2005
//
#ifdef __cplusplus
extern "C" {
#endif // __cplusplus
#pragma warning(disable:4200)
#pragma warning(disable:4201)
#include <stdarg.h>
#include <stdio.h>
#include <stddef.h>
#include <initguid.h>
#define  _W2K_SPY_SYS_
#include <ntddk.h>
#include "w2k_spy.h"
#define NTSTRSAFE_LIB
#include <ntstrsafe.h>
#ifdef __cplusplus
}
#endif // __cplusplus


//#include "DrvInfo.h"
//#include "w2k_def.h"
#include "testdrv.h"
