# Automatically generated by configure - do not modify
TARGET_DIR=objs
TARGET_CONFIG_MAKE=config.make
TARGET_CFLAGS=-I$(SRC_PATH)/android/config/target-$(TARGET_ARCH)
SRC_PATH=/home/tony/project/android4.3_r2.2/external/qemu_droidscope
