// intrface.h
//
// Generated by C DriverWizard 3.2.0 (Build 2485)
// Requires DDK Only
// File created on 11/15/2005
//

// GUID definition are required to be outside of header inclusion pragma to avoid
// error during precompiled headers.
//

#ifndef __INTRFACE_H__
#define __INTRFACE_H__

#define FILE_DEVICE_TESTDRV  0x8000

// Define Interface reference/dereference routines for
// Interfaces exported by IRP_MN_QUERY_INTERFACE

#define TESTDRV_IOCTL(index) \
    CTL_CODE(FILE_DEVICE_TESTDRV, index, METHOD_BUFFERED, FILE_READ_DATA)


#endif // __INTRFACE_H__
