ZLIB_VERSION   := zlib-1.2.3
LIBPNG_VERSION := libpng-1.2.19

ZLIB_DIR    = $(SRC_PATH)/distrib/$(ZLIB_VERSION)
LIBPNG_DIR := $(SRC_PATH)/distrib/$(LIBPNG_VERSION)

include $(ZLIB_DIR)/Makefile
include $(LIBPNG_DIR)/Makefile
