//
// resource.h
//
// Generated by C DriverWizard 3.2.0 (Build 2485)
// Requires DDK Only
// File created on 11/15/2005
//
#define IDC_DEVICE_INSTANCE_LIST        1001
#define IDC_OPEN_BUTTON                 1002
#define IDC_CLOSE_BUTTON                1003
#define IDC_OP_TYPE_COMBO               1004
#define IDC_IN_DATA_EDIT                1006
#define IDC_RETURN_LENGTH_EDIT          1008
#define IDC_IN_SIZE_EDIT                1009
#define IDC_OUT_DATA_EDIT               1010
#define IDC_OUT_SIZE_EDIT               1011
#define IDC_ERROR_CODE_EDIT             1012
#define IDC_OPERATION_TYPE_STATIC       1013
#define IDC_DEVICE_INSTANCE_STATIC      1014
#define IDC_IN_DATA_STATIC              1015
#define IDC_OUT_DATA_STATIC             1016
#define IDC_IN_SIZE_STATIC              1017
#define IDC_OUT_SIZE_STATIC             1018
#define IDC_CANCEL_IO_BUTTON            1019
#define IDC_EXECUTE_BUTTON              1020
#define IDC_SELECTED_DEVICE_EDIT        1021
#define IDC_SELECTED_DEVICE_STATIC      1022

