//
// testdrvApp.h
//
// Generated by C DriverWizard 3.2.0 (Build 2485)
// Requires DDK Only
// File created on 11/15/2005
//
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <process.h>
#include <commctrl.h>
#include <tchar.h>
#include <setupapi.h>
#include <initguid.h>
#include <winioctl.h>
#include <process.h>
#include <assert.h>
#include <dbt.h>
#include "resource.h"

#include "..\intrface.h"

#define MAX_STRING_LENGTH       500

typedef VOID (*TESTDRV_IO_CALLBACK)(PVOID Context);

// Structure used to store I/O information for delayed
// processing of overlapped requests
typedef struct _TESTDRV_LIST_ITEM
{
    struct _TESTDRV_LIST_ITEM*  Next;
    struct _TESTDRV_LIST_ITEM*  Previous;
    OVERLAPPED                  IoOverlapped;
    PCHAR                       InBuffer;
    PCHAR                       OutBuffer;
    ULONG                       InSize;
    ULONG                       OutSize;
    ULONG                       ReturnLength;
    ULONG                       Error;
    TESTDRV_IO_CALLBACK         Callback;
} TESTDRV_LIST_ITEM, *PTESTDRV_LIST_ITEM;

extern HANDLE           g_hDevice;
extern TESTDRV_LIST_ITEM    g_IoList;
extern CRITICAL_SECTION g_IoListLock;

ULONG testdrvExecuteIo(HWND hDlg);
UINT __stdcall testdrvIoCompletionThread(PVOID Context);
VOID testdrvOutputText(LPCTSTR Format, ...);
VOID testdrvOutputBuffer(PVOID Buffer, ULONG Size);

