/* This file was autogenerated by 'android-configure.sh' */
#define CONFIG_QEMU_SHAREDIR   "/usr/local/share/qemu"
#if defined(__x86_64__)
#define HOST_X86_64    1
#define HOST_LONG_BITS  64
#elif defined(__i386__)
#define HOST_I386    1
#define HOST_LONG_BITS  32
#else
#error Unknown architecture for codegen
#endif

#define CONFIG_GDBSTUB  1
#define CONFIG_SLIRP    1
#define CONFIG_SKINS    1
#define CONFIG_TRACE    1
#define QEMU_VERSION    "0.10.50"
#define QEMU_PKGVERSION "Android"
#define CONFIG_WIN32   1
#define CONFIG_ANDROID       1
#define CONFIG_ANDROID_OPENGLES 1
