/* Automagically generated by mkallmodules, DO NOT EDIT */

#ifndef LLCONF
#  include <llconf/file.h>
#else
#  include "file.h"
#endif

#ifndef LLCONF
#  include <llconf/shell.h>
#else
#  include "shell.h"
#endif

#ifndef LLCONF
#  include <llconf/properties.h>
#else
#  include "properties.h"
#endif

#ifndef LLCONF
#  include <llconf/table.h>
#else
#  include "table.h"
#endif

#ifndef LLCONF
#  include <llconf/ifupdown.h>
#else
#  include "ifupdown.h"
#endif

#ifndef LLCONF
#  include <llconf/pair.h>
#else
#  include "pair.h"
#endif

#ifndef LLCONF
#  include <llconf/ppp.h>
#else
#  include "ppp.h"
#endif

#ifndef LLCONF
#  include <llconf/ini.h>
#else
#  include "ini.h"
#endif

#ifndef LLCONF
#  include <llconf/tz.h>
#else
#  include "tz.h"
#endif

#ifndef LLCONF
#  include <llconf/route.h>
#else
#  include "route.h"
#endif

#ifndef LLCONF
#  include <llconf/iproute.h>
#else
#  include "iproute.h"
#endif

#ifndef LLCONF
#  include <llconf/pslave.h>
#else
#  include "pslave.h"
#endif

#ifndef LLCONF
#  include <llconf/ipsec.h>
#else
#  include "ipsec.h"
#endif

#ifndef LLCONF
#  include <llconf/funcexpr.h>
#else
#  include "funcexpr.h"
#endif

#ifndef LLCONF
#  include <llconf/cyconf.h>
#else
#  include "cyconf.h"
#endif

#ifndef LLCONF
#  include <llconf/syslogng.h>
#else
#  include "syslogng.h"
#endif

#ifndef LLCONF
#  include <llconf/iptables.h>
#else
#  include "iptables.h"
#endif

#ifndef LLCONF
#  include <llconf/mgetty.h>
#else
#  include "mgetty.h"
#endif

#ifndef LLCONF
#  include <llconf/snmpd.h>
#else
#  include "snmpd.h"
#endif

#ifndef LLCONF
#  include <llconf/conserver.h>
#else
#  include "conserver.h"
#endif

#ifndef LLCONF
#  include <llconf/cron.h>
#else
#  include "cron.h"
#endif

#ifndef LLCONF
#  include <llconf/dhcp.h>
#else
#  include "dhcp.h"
#endif

#ifndef LLCONF
#  include <llconf/dhcp_leases.h>
#else
#  include "dhcp_leases.h"
#endif

#ifndef LLCONF
#  include <llconf/python.h>
#else
#  include "python.h"
#endif

#ifndef LLCONF
#  include <llconf/xinetd.h>
#else
#  include "xinetd.h"
#endif

void register_all();
