/* Automagically generated by mkallmodules, DO NOT EDIT */

#include <stdio.h>
#include <stdlib.h>
#include "modules.h"
#include "nodes.h"
#include "allmodules.h"

void register_all()
{
  register_file(NULL);
  register_shell(NULL);
  register_properties(NULL);
  register_table(NULL);
  register_ifupdown(NULL);
  register_pair(NULL);
  register_ppp(NULL);
  register_ini(NULL);
  register_tz(NULL);
  register_route(NULL);
  register_iproute(NULL);
  register_pslave(NULL);
  register_ipsec(NULL);
  register_funcexpr(NULL);
  register_cyconf(NULL);
  register_syslogng(NULL);
  register_iptables(NULL);
  register_mgetty(NULL);
  register_snmpd(NULL);
  register_conserver(NULL);
  register_cron(NULL);
  register_dhcp(NULL);
  register_dhcp_leases(NULL);
  register_python(NULL);
  register_xinetd(NULL);
}
